# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-09 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import excelapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExcelData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=100, null=True, verbose_name='Heading')),
                ('value', models.CharField(max_length=100, null=True, verbose_name='Value')),
                ('priority', models.IntegerField(verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Excel Data',
                'verbose_name_plural': 'Excel Datas',
            },
        ),
        migrations.CreateModel(
            name='ExcelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100, null=True, verbose_name='File name')),
                ('attachment', models.FileField(upload_to='uploads/attachments', validators=[excelapp.models.validate_file_extension], verbose_name='Attachment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Excel File',
                'verbose_name_plural': 'Excel Files',
            },
        ),
        migrations.CreateModel(
            name='ExcelFileData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(verbose_name='Priority')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('excel_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelapp.ExcelFile')),
            ],
            options={
                'verbose_name': 'Excel File Data',
                'verbose_name_plural': 'Excel File Datas',
            },
        ),
        migrations.AddField(
            model_name='exceldata',
            name='excel_file_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='excelapp.ExcelFileData'),
        ),
    ]
